services:
  steam-headless:
    volumes:
      - ./scripts/res-switch:/usr/bin/res-switch:ro
      - ./scripts/res-reset:/usr/bin/res-reset:ro
      - ./sunshine/apps.json:/home/default/.config/sunshine/apps.json:ro
      