services:
  steam-headless:
    volumes:
      - ./scripts/res-switch:/home/default/bin/res-switch:ro
      - ./scripts/res-reset:/home/default/bin/res-reset:ro
      - ./install/99-install-res-switch.sh:/opt/res-switch/99-install-res-switch.sh:ro
      