services:
  steam-headless:
    volumes:
      - ./scripts/res-switch:/home/default/bin/res-switch:ro
      - ./scripts/res-reset:/home/default/bin/res-reset:ro
      - ./init.d/99-install-res-switch.sh:/home/default/init.d/99-install-res-switch.sh:ro
      